export const initialData = [
    {
        id: 1000,
        datetime: 0,
        location: "",
        reportedBy: 1223,
        employeesInvolved: "",
        injury: "",
        description: "",
        category: "",
        actionsTaken: "",
        existingBarriers: "",
        preventiveMeasures: "",
    },
    {
        id: 1001,
        datetime: 0,
        location: "",
        reportedBy: 1223,
        employeesInvolved: "",
        injury: "",
        description: "",
        category: "",
        actionsTaken: "",
        existingBarriers: "",
        preventiveMeasures: "",
    },
    {
        id: 1057,
        datetime: 0,
        location: "",
        reportedBy: 1223,
        employeesInvolved: "",
        injury: "",
        description: "",
        category: "",
        actionsTaken: "",
        existingBarriers: "",
        preventiveMeasures: "",
    },
    {
        id: 1207,
        datetime: 0,
        location: "",
        reportedBy: 1223,
        employeesInvolved: "",
        injury: "",
        description: "",
        category: "",
        actionsTaken: "",
        existingBarriers: "",
        preventiveMeasures: "",
    },
    {
        id: 2347,
        datetime: 0,
        location: "",
        reportedBy: 1223,
        employeesInvolved: "",
        injury: "",
        description: "",
        category: "",
        actionsTaken: "",
        existingBarriers: "",
        preventiveMeasures: "",
    },
    {
        id: 6100,
        datetime: 0,
        location: "",
        reportedBy: 1223,
        employeesInvolved: "",
        injury: "",
        description: "",
        category: "",
        actionsTaken: "",
        existingBarriers: "",
        preventiveMeasures: "",
    },
];

export const initialFields = [
    { name: "id", label: "Incident ID", columnWidth: 90, type: "text" },
    { name: "datetime", label: "Date Time", columnWidth: 220, type: "datetime-local" },
    { name: "location", label: "Location", columnWidth: 150, type: "text" },
    { name: "reportedBy", label: "Reported By", columnWidth: 150, type: "text" },
    { name: "employeesInvolved", label: "Employees Involved", columnWidth: 150, type: "text" },
    { name: "injury", label: "Injury", columnWidth: 150, type: "text" },
    { name: "description", label: "Description", columnWidth: 150, type: "text" },
    { name: "category", label: "Category", columnWidth: 150, type: "text" },
    { name: "actionsTaken", label: "Actions Taken", columnWidth: 150, type: "text" },
    { name: "existingBarriers", label: "Existing Barriers", columnWidth: 150, type: "text" },
    { name: "preventiveMeasures", label: "Preventive Measures", columnWidth: 150, type: "text" },
];
