name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [frontend, backend]
        include:
          - component: frontend
            language: javascript
            path: frontend
          - component: backend
            language: java
            path: backend
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      if: matrix.language == 'javascript'
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Set up JDK 17
      if: matrix.language == 'java'
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install dependencies (Frontend)
      if: matrix.language == 'javascript'
      run: |
        cd "${{ matrix.path }}"
        npm install

    - name: Install dependencies (Backend)
      if: matrix.language == 'java'
      run: |
        cd "${{ matrix.path }}"
        mvn clean install

    # Frontend build and test
    - name: Build Frontend
      if: matrix.language == 'javascript'
      run: |
        cd "${{ matrix.path }}"
        npm run build
    - name: Test Frontend
      if: matrix.language == 'javascript'
      run: |
        cd "${{ matrix.path }}"
        npm test

    # Backend build and test
    - name: Build Backend
      if: matrix.language == 'java'
      run: |
        cd "${{ matrix.path }}"
        mvn package
    - name: Test Backend
      if: matrix.language == 'java'
      run: |
        cd "${{ matrix.path }}"
        mvn test
